### ISSUE TITLE
Input validation

### ISSUE THREAD

**Issue by raquelalegre** [UCL-RITS/GFR-calculator#17]
At the least check things that should be numbers are numbers and they are no blanks.
It time allows, check values are inside ranges given my Emmanuel, if he agrees.

**Comment by raquelalegre** [comment]
Emmanuel [gave some validation ranges](https://github.com/UCL-RITS/GFR-calculator/wiki/Meeting-mid-progress):
* Age from 18 to 100
* Sodium from 110 to 160
* Rest of values with no boundaries

It'd be nice to use [bootstrap glyphicons](http://www.w3schools.com/Bootstrap/bootstrap_forms_inputs2.asp) for validation and assign the `span` where they are placed a hover action that [shows a tooltip of what the error message is about](http://stackoverflow.com/questions/19688974/bootstrap-3-tooltip-over-glyphicon). 

Validation as-you-type if there is an easy way would be nice.

**Comment by raquelalegre** [comment]
@dpshelio found we don't need to do most of the validation since bootstrap has that built in, although it was tricky to set up. See 6241d1d. 

However this validation doesn't work for Safari and iOS and we'll have to work around it.

**Comment by dpshelio** [comment]
Closed with: 7b7490d1a8cb64bf5fb2fea4f75f5bbc062c134e and 5aa0c9a8be8a9b38e78a346c6191fbb2b2cf3e97
