### ISSUE TITLE
Decimal precision

### ISSUE THREAD

**Issue by dpshelio** [UCL-RITS/GFR-calculator#18]
What's the decimal precision we want to show in the result? What are the one allowed for the inputs?

**Comment by raquelalegre** [comment]
Added this to a list of questions I'm compiling to ask Emmanuel on the [f2f meeting](https://github.com/UCL-RITS/GFR-calculator/wiki/Meeting-mid-progress).

**Comment by raquelalegre** [comment]
In the meeting, Emmanuel said decimals positions should be up to 3 in the result and up to 1 in the input values, except for Sodium and Age

**Comment by raquelalegre** [comment]
@dpshelio I think we can close this, right?

**Comment by dpshelio** [comment]
01ae04fa1 clossed it
