### ISSUE TITLE
Changes to form

### ISSUE THREAD

**Issue by dpshelio** [UCL-RITS/GFR-calculator#22]
From closed #21 
- [x] Button groups need improving, can be done with Radio buttons, although I couldn't make them look nice. They should also be justified, ` .btn-group-justified` didn't work. Also the colour doesn't match the rest of the screen. And more importantly, they don't stay down after pressed :( 
- [ ] Ascites maybe should be a checkbox instead of a button group. I'd like to try again with [this](http://getbootstrap.com/components/#input-groups-checkboxes-radios), which didn't work yesterday.
- [ ] Dropdowns for the units need corrections:
   - [ ] Should be done with [this](http://getbootstrap.com/components/#input-groups-buttons-dropdowns).
   - [ ] The content is wrong because I made the units up.
   - [x] The content doesn't stay after choosing the option because it's a dropdown button as opposed to a normal dropdown.
   - [ ] The style doesn't seem in line with the rest of the form.
   - [ ] The alignment doesn't match the rest of the row.
- [x] Spacing between rows needs revising, I just added `<br/>` which is so so so wrong.
- [x] I'm not sure where is best to show the result. Maybe we could just put it on a box to the right of the calculator? 
   - [x] The element that contains the well (the area between header and footer) needs to be updated to use bootstrap grid for aligning instead of indigo's.
   - [x] The JS needs updating to read the gender/ascites choice, as well as the

**Comment by dpshelio** [comment]
- Ascites at the moment is a radio button that cannot be unselected, we need to change it to box.
- Dropdown can be improved and set by default the ones from the equation.

**Comment by raquelalegre** [comment]
Comments about dropdowns in the units don't apply any more because we have to get rid of them.
Same for ascites.
Rest is done, so closing.
