### ISSUE TITLE
Prepare release with latest changes requested

### ISSUE THREAD

**Issue by raquelalegre** [UCL-RITS/GFR-calculator#28]
Emmanuel sent the details on what he'd like changed before the release:

1. Please use male as the reference point in the equation and also in the information (replace therefore in the calculator 0.809 (if female) with 1.236 (if male) as in the excel data sheet). David, can you please remind me what is the constant to use to get similar values with female as with male?
2. Upper limits of normal: please use 5 for INR, 400 mmol/L for creatinine (equivalent to 4.5 mg/dl) and 30 mmol/L for urea (or 84 mg/dl).

**Comment by dpshelio** [comment]
latest commits: 5df4efc80d69a972878f295c304f89ba2182a36f and ccbd2764c4537af8128a26adb3696e51f4a2acaa closes this.
