### ISSUE TITLE
Under construction dummy website

### ISSUE THREAD

**Issue by raquelalegre** [UCL-RITS/GFR-calculator#3]
Use UCL Azure allocation to host an "Under construction" web so Emmanuel can link to it from his paper. 

- [x] Choose technology to work on (AngularJS? There's many online BMI calculator examples we could reuse)
- [x] Make sure it works well on mobile phones.
- [ ] Test it agains several browsers. Maybe something like [this](https://www.browserling.com)?
- [x] Add Google Analytics?
- [ ] Probably needs to get the RFH logo/header/link as well. See [here](https://www.royalfree.nhs.uk).
- [x] Consider using Indigo, see https://github.com/UCL-RITS/indigo-jekyll
- [ ] Emmanuel mentioned his results had to appear first on Google. That'd be a whole entire separate project on SEO, but [these tips might help](http://cristersmedia.com/how-do-i-get-my-website-on-the-first-page-of-google).

**Comment by raquelalegre** [comment]
Under construction site ready as gh-pages. See http://rits.github-pages.ucl.ac.uk/GFR-calculator/

Still waiting for the redirect stuff to be put in place :-/

**Comment by raquelalegre** [comment]
Redirect done, but it's changing the URL when redirecting. David is chasing Adrian to make the redirect use forward with masking.

**Comment by raquelalegre** [comment]
@dpshelio did you get Adrian to do this before the holiday? 

If so, just close issue since all subtasks above have been spawned into issues.

**Comment by raquelalegre** [comment]
@dpshelio any news from Adrian?

**Comment by raquelalegre** [comment]
@dpshelio knows what to do. Something about a cname file.

**Comment by raquelalegre** [comment]
@dpshelio can you update on what was done and close?

**Comment by raquelalegre** [comment]
@dpshelio can you update this so we know what was done in case we need it for reference in the future?

**Comment by dpshelio** [comment]
The DNS entry for  rfh-cirrhosis-gfr.ucl.ac.uk has been changed to point to ucl-rits.github.io
The repository CNAME then name it as `rfh-cirrhosis-gfr.ucl.ac.uk`, github does the linkins to the project.
This is the host output:
```sh
$ host rfh-cirrhosis-gfr.ucl.ac.uk                                                                                                                                                                                                                                      rfh-cirrhosis-gfr.ucl.ac.uk is an alias for ucl-rits.github.io.
ucl-rits.github.io is an alias for github.map.fastly.net.
github.map.fastly.net has address 151.101.16.133
```
