### ISSUE TITLE
Write disclaimer and intro

### ISSUE THREAD

**Issue by raquelalegre** [UCL-RITS/GFR-calculator#4]
Emmanuel is going to send us a disclaimer for the header of the calculator, after consulting with his legal team.

**Comment by raquelalegre** [comment]
Just emailed him about this, also asking for a description to add to the web explaining what the formula does.

**Comment by raquelalegre** [comment]
Emmanuel agreed to send this next week.
Introduction should appear before the calculator and disclaimer at the end.

**Comment by dpshelio** [comment]
Done! 985fa182f7350db94e0363919e3a818372cbb0a8
