### ISSUE TITLE
Get GFR formula from Emmanuel

### ISSUE THREAD

**Issue by raquelalegre** [UCL-RITS/GFR-calculator#7]
We asked him before for it but never got it. Chase him again on this.

**Comment by raquelalegre** [comment]
Just pinged Emmanuel about this.

**Comment by raquelalegre** [comment]
He replied. The formula is in his paper which I placed [here](https://github.com/UCL-RITS/GFR-calculator/tree/master/docs).

**Comment by raquelalegre** [comment]
From the formular, these are the user inputs needed:
* Gender
* Age
* Ascites
* Creatinine
* Sodium
* Urea
* International Normalized Ratio

We still need to know from Emmanuel:

* What different options should we display to pick up level of ascites?
* Different possible units for creatinine, sodium and urea. 
* What are default/normal levels?

**Comment by raquelalegre** [comment]
Emmanuel sent some sample data where he was using a formula slightly different from that in the paper. We're waiting to get the final formula from him next Monday.

**Comment by dpshelio** [comment]
Solved! Using the one from the paper
