### ISSUE TITLE
Choose technology to work on

### ISSUE THREAD

**Issue by raquelalegre** [UCL-RITS/GFR-calculator#8]
The webapp is just a static web form containing a few fields and returning a result calculated with Emmanuel's GFR formula. Some inputs can be given in two possible units, so it would be nice it works like a BMI calculator where you can switch metric/imperial like [this].(http://embed.plnkr.co/PA3cqQ/). I think Emmanuel said units are different for patients in the US.

Note we are still to get this details from Emmanuel, see #7.

Things to choose from or combine:
  * [VanillaJS](http://vanilla-js.com/).
  * [AngularJS](https://angularjs.org).
  * Some other JS library from the thousands of them out there. 
  * We could also use [Bootstrap](http://getbootstrap.com/components/). 
  * Also I don't know exactly what [Indigo](https://github.com/UCL-WAMS/indigo) does, but we should take a look because James suggested we use it. I think it includes the UCL web styling libraries? No idea yet. By the look of it seems like an equivalent to Bootstrap.

**Comment by raquelalegre** [comment]
I've had a look at the information about Indigo [here](https://www.ucl.ac.uk/indigo).
It has some pre-built examples for forms [here](https://www.ucl.ac.uk/indigo/patterns/form1). Indigo looks cool and makes some things easier, specially styling, but not sure how easy it is to expand. We need to check if we can do the switch context button that calculates the result for US measurements and non-US. Also there is just [a few different layouts](https://www.ucl.ac.uk/indigo/design-foundation/indigo-foundation/grid-system) available. Does any of them fit the website we want to make?

By the way, Emmanuel sent this reference website he wants us to base our work on: http://www.mdcalc.com/meld-score-model-end-stage-liver-disease-12-older/

**Comment by raquelalegre** [comment]
The reference web form has just changed over the weekend. It used to display a toggle to choose US-metrics, but now each field has a dropdown to choose units. Maybe this last option is better in case there are people with mixed metrics? We should ask Emmanuel what design he prefers.

**Comment by dpshelio** [comment]
We are mixing bootstrap and indigo Yay!
